[package]
name = "dola"
version = "0.1.0"
edition = "2024"

[dependencies]
float16 = "0.1.3"
float8 = "0.2.1"
glob = "0.3.2"
image = "0.25.6"
indicatif = "0.17.11"
ndarray = "0.16.1"
rand = "0.9.1"
tokio = {version="1.45.1", features = ["full"]}
